
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace banSach.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ChiTietGioHang
{

    public string MaChiTiet { get; set; }

    public string MaGioHang { get; set; }

    public string MaSach { get; set; }

    public Nullable<int> SoLuong { get; set; }

    public Nullable<decimal> DonGia { get; set; }



    public virtual GioHang GioHang { get; set; }

    public virtual Sach Sach { get; set; }

}

}
