
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace banSach.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DiaChi
{

    public int Id { get; set; }

    public string MaTinhThanh { get; set; }

    public string TenTinhThanh { get; set; }

    public string MaQuanHuyen { get; set; }

    public string TenQuanHuyen { get; set; }

    public string MaPhuongXa { get; set; }

    public string TenPhuongXa { get; set; }

    public Nullable<decimal> PhiVanChuyen { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

}

}
