
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace banSach.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DonDatHang
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DonDatHang()
    {

        this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();

        this.SuDungMaGiamGias = new HashSet<SuDungMaGiamGia>();

        this.ThanhToans = new HashSet<ThanhToan>();

    }


    public string MaDonHang { get; set; }

    public string HoTen { get; set; }

    public string SoDienThoai { get; set; }

    public string Email { get; set; }

    public string DiaChi { get; set; }

    public Nullable<System.DateTime> NgayDat { get; set; }

    public string TrangThai { get; set; }

    public Nullable<int> PhuongThucThanhToan { get; set; }

    public string MaGiamGia { get; set; }

    public Nullable<decimal> TongTien { get; set; }

    public Nullable<decimal> PhiVanChuyen { get; set; }

    public string GhiChu { get; set; }

    public Nullable<System.DateTime> NgayGiao { get; set; }

    public Nullable<System.DateTime> NgayHoanThanh { get; set; }

    public string MaKH { get; set; }

    public string LyDoHuy { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SuDungMaGiamGia> SuDungMaGiamGias { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ThanhToan> ThanhToans { get; set; }

    public virtual KhachHang KhachHang { get; set; }

}

}
