
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace banSach.Models
{

using System;
    using System.Collections.Generic;
    
public partial class KhachHang
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public KhachHang()
    {

        this.GioHangs = new HashSet<GioHang>();

        this.DanhGias = new HashSet<DanhGia>();

        this.YeuThiches = new HashSet<YeuThich>();

        this.BookViews = new HashSet<BookView>();

        this.SuDungMaGiamGias = new HashSet<SuDungMaGiamGia>();

        this.DonDatHangs = new HashSet<DonDatHang>();

    }


    public string MaKH { get; set; }

    public string HoTen { get; set; }

    public string SoDienThoai { get; set; }

    public string MatKhau { get; set; }

    public string Email { get; set; }

    public string DiaChi { get; set; }

    public Nullable<System.DateTime> NgaySinh { get; set; }

    public Nullable<int> TrangThai { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GioHang> GioHangs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DanhGia> DanhGias { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<YeuThich> YeuThiches { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BookView> BookViews { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SuDungMaGiamGia> SuDungMaGiamGias { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DonDatHang> DonDatHangs { get; set; }

}

}
