
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace banSach.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MaGiamGia
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MaGiamGia()
    {

        this.SuDungMaGiamGias = new HashSet<SuDungMaGiamGia>();

    }


    public string MaCode { get; set; }

    public string TenChuongTrinh { get; set; }

    public Nullable<int> PhanTramGiam { get; set; }

    public Nullable<decimal> SoTienGiam { get; set; }

    public Nullable<System.DateTime> NgayBatDau { get; set; }

    public Nullable<System.DateTime> NgayKetThuc { get; set; }

    public Nullable<int> SoLuongMa { get; set; }

    public Nullable<int> DaSuDung { get; set; }

    public Nullable<bool> TrangThai { get; set; }

    public Nullable<decimal> DonHangToiThieu { get; set; }

    public Nullable<decimal> GiamToiDa { get; set; }

    public string LoaiMa { get; set; } // "percent", "fixed", or "freeship"



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SuDungMaGiamGia> SuDungMaGiamGias { get; set; }

}

}
