
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace banSach.Models
{

using System;
    using System.Collections.Generic;
    
public partial class NhanVien
{

    public string MaNhanVien { get; set; }

    public string HoTen { get; set; }

    public string SoDienThoai { get; set; }

    public string Email { get; set; }

    public string TenTK { get; set; }

    public string MatKhau { get; set; }

    public string MaCV { get; set; }

    public Nullable<bool> TrangThai { get; set; }



    public virtual ChucVu ChucVu { get; set; }

}

}
