
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace banSach.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sach
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sach()
    {

        this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();

        this.ChiTietGioHangs = new HashSet<ChiTietGioHang>();

        this.VietSaches = new HashSet<VietSach>();

        this.DanhGias = new HashSet<DanhGia>();

        this.YeuThiches = new HashSet<YeuThich>();

        this.BookViews = new HashSet<BookView>();

    }


    public string MaSach { get; set; }

    public string TenSach { get; set; }

    public string Hinh { get; set; }

    public Nullable<decimal> GiaBan { get; set; }

    public string MoTa { get; set; }

    public string MaNXB { get; set; }

    public Nullable<System.DateTime> NgayNhapHang { get; set; }

    public Nullable<int> SoLuongTon { get; set; }

    public string MaLoai { get; set; }

    public Nullable<int> Status { get; set; }

    public Nullable<decimal> GiaChietKhau { get; set; }

    public Nullable<int> SoTrang { get; set; }

    public Nullable<int> NamXuatBan { get; set; }

    public Nullable<int> TrongLuong { get; set; }

    public string KichThuoc { get; set; }

    public string LoaiBia { get; set; }

    public Nullable<int> SoLuongBan { get; set; }

    public Nullable<double> DiemDanhGiaTB { get; set; }

    public Nullable<int> SoLuotDanhGia { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChiTietGioHang> ChiTietGioHangs { get; set; }

    public virtual Loai Loai { get; set; }

    public virtual NhaXuatBan NhaXuatBan { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VietSach> VietSaches { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DanhGia> DanhGias { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<YeuThich> YeuThiches { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BookView> BookViews { get; set; }

}

}
