
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace banSach.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SuDungMaGiamGia
{

    public int Id { get; set; }

    public string MaCode { get; set; }

    public string MaDonHang { get; set; }

    public string MaKH { get; set; }

    public decimal SoTienGiam { get; set; }

    public System.DateTime NgaySuDung { get; set; }



    public virtual DonDatHang DonDatHang { get; set; }

    public virtual KhachHang KhachHang { get; set; }

    public virtual MaGiamGia MaGiamGia { get; set; }

}

}
