
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace banSach.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ThanhToan
{

    public string MaThanhToan { get; set; }

    public string MaDonHang { get; set; }

    public string MaGiaoDich { get; set; }

    public int PhuongThucThanhToan { get; set; }

    public string TrangThaiThanhToan { get; set; }

    public decimal SoTienThanhToan { get; set; }

    public Nullable<System.DateTime> NgayThanhToan { get; set; }

    public System.DateTime NgayTao { get; set; }

    public string GhiChu { get; set; }



    public virtual DonDatHang DonDatHang { get; set; }

}

}
